### ISSUE TITLE
This way to get all mint address too low performance !

### ISSUE THREAD

**Issue by defi0x1** [metaplex-foundation/get-collection#1]

**Comment by vinkent-dev** [comment]
@docongminh : Please can you sharing more information about this issue, thank and so respect!

**Comment by samuelvanderwaal** [comment]
A better way is coming.

**Comment by devstein** [comment]
Hi @samuelvanderwaal excited to hear a better way is on its way. What's the best place to follow for updates on the upcoming approach?

**Comment by samuelvanderwaal** [comment]
> Hi @samuelvanderwaal excited to hear a better way is on its way. What's the best place to follow for updates on the upcoming approach?

https://twitter.com/MetaplexStatus
and
https://twitter.com/metaplex
